import { authOptions } from '@/app/api/[...nextauth]/route';
import Layout from '@/components/core/Layout';
import Provider from '@/context/clientContext';
import type { Metadata } from 'next';
import { getServerSession } from 'next-auth/next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider session={session}>
          <Layout>{children}</Layout>
        </Provider>
      </body>
    </html>
  );
}
